services:
  - type: web
    name: chatbot-pdf-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
